spring:
#  profiles:
#    active: dev
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl